//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using SStorm.CTH.DAL.EntityClasses;
using SStorm.CTH.DAL.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace SStorm.CTH.DAL.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the CTHCancerGrade entity</summary>
		public EntityQuery<CTHCancerGradeEntity> CTHCancerGrade { get { return Create<CTHCancerGradeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCancerHistologic entity</summary>
		public EntityQuery<CTHCancerHistologicEntity> CTHCancerHistologic { get { return Create<CTHCancerHistologicEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCancerMolecular entity</summary>
		public EntityQuery<CTHCancerMolecularEntity> CTHCancerMolecular { get { return Create<CTHCancerMolecularEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCancerSide entity</summary>
		public EntityQuery<CTHCancerSideEntity> CTHCancerSide { get { return Create<CTHCancerSideEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCancerStaging entity</summary>
		public EntityQuery<CTHCancerStagingEntity> CTHCancerStaging { get { return Create<CTHCancerStagingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCancerType entity</summary>
		public EntityQuery<CTHCancerTypeEntity> CTHCancerType { get { return Create<CTHCancerTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHChemoLab entity</summary>
		public EntityQuery<CTHChemoLabEntity> CTHChemoLab { get { return Create<CTHChemoLabEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHChemotherapyProtocol entity</summary>
		public EntityQuery<CTHChemotherapyProtocolEntity> CTHChemotherapyProtocol { get { return Create<CTHChemotherapyProtocolEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCycleDrug entity</summary>
		public EntityQuery<CTHCycleDrugEntity> CTHCycleDrug { get { return Create<CTHCycleDrugEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHCycleLab entity</summary>
		public EntityQuery<CTHCycleLabEntity> CTHCycleLab { get { return Create<CTHCycleLabEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDoctor entity</summary>
		public EntityQuery<CTHDoctorEntity> CTHDoctor { get { return Create<CTHDoctorEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDoseUnit entity</summary>
		public EntityQuery<CTHDoseUnitEntity> CTHDoseUnit { get { return Create<CTHDoseUnitEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDrug entity</summary>
		public EntityQuery<CTHDrugEntity> CTHDrug { get { return Create<CTHDrugEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDrugAttachment entity</summary>
		public EntityQuery<CTHDrugAttachmentEntity> CTHDrugAttachment { get { return Create<CTHDrugAttachmentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDrugDay entity</summary>
		public EntityQuery<CTHDrugDayEntity> CTHDrugDay { get { return Create<CTHDrugDayEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHDrugSymptom entity</summary>
		public EntityQuery<CTHDrugSymptomEntity> CTHDrugSymptom { get { return Create<CTHDrugSymptomEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHImaging entity</summary>
		public EntityQuery<CTHImagingEntity> CTHImaging { get { return Create<CTHImagingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHKimoSurvey entity</summary>
		public EntityQuery<CTHKimoSurveyEntity> CTHKimoSurvey { get { return Create<CTHKimoSurveyEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHLab entity</summary>
		public EntityQuery<CTHLabEntity> CTHLab { get { return Create<CTHLabEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHLabDetail entity</summary>
		public EntityQuery<CTHLabDetailEntity> CTHLabDetail { get { return Create<CTHLabDetailEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHLabDetailCondition entity</summary>
		public EntityQuery<CTHLabDetailConditionEntity> CTHLabDetailCondition { get { return Create<CTHLabDetailConditionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHLabGroup entity</summary>
		public EntityQuery<CTHLabGroupEntity> CTHLabGroup { get { return Create<CTHLabGroupEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHLabGroupLab entity</summary>
		public EntityQuery<CTHLabGroupLabEntity> CTHLabGroupLab { get { return Create<CTHLabGroupLabEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHMainCancerImage entity</summary>
		public EntityQuery<CTHMainCancerImageEntity> CTHMainCancerImage { get { return Create<CTHMainCancerImageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHNotification entity</summary>
		public EntityQuery<CTHNotificationEntity> CTHNotification { get { return Create<CTHNotificationEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHOperator entity</summary>
		public EntityQuery<CTHOperatorEntity> CTHOperator { get { return Create<CTHOperatorEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPathologyReportType entity</summary>
		public EntityQuery<CTHPathologyReportTypeEntity> CTHPathologyReportType { get { return Create<CTHPathologyReportTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatient entity</summary>
		public EntityQuery<CTHPatientEntity> CTHPatient { get { return Create<CTHPatientEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientAssessment entity</summary>
		public EntityQuery<CTHPatientAssessmentEntity> CTHPatientAssessment { get { return Create<CTHPatientAssessmentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientClinicalData entity</summary>
		public EntityQuery<CTHPatientClinicalDataEntity> CTHPatientClinicalData { get { return Create<CTHPatientClinicalDataEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientDrug entity</summary>
		public EntityQuery<CTHPatientDrugEntity> CTHPatientDrug { get { return Create<CTHPatientDrugEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientImaging entity</summary>
		public EntityQuery<CTHPatientImagingEntity> CTHPatientImaging { get { return Create<CTHPatientImagingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientIntialLab entity</summary>
		public EntityQuery<CTHPatientIntialLabEntity> CTHPatientIntialLab { get { return Create<CTHPatientIntialLabEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientPathologyReport entity</summary>
		public EntityQuery<CTHPatientPathologyReportEntity> CTHPatientPathologyReport { get { return Create<CTHPatientPathologyReportEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientSurgery entity</summary>
		public EntityQuery<CTHPatientSurgeryEntity> CTHPatientSurgery { get { return Create<CTHPatientSurgeryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPatientSymptom entity</summary>
		public EntityQuery<CTHPatientSymptomEntity> CTHPatientSymptom { get { return Create<CTHPatientSymptomEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPaymentType entity</summary>
		public EntityQuery<CTHPaymentTypeEntity> CTHPaymentType { get { return Create<CTHPaymentTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPermission entity</summary>
		public EntityQuery<CTHPermissionEntity> CTHPermission { get { return Create<CTHPermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPermissionGroup entity</summary>
		public EntityQuery<CTHPermissionGroupEntity> CTHPermissionGroup { get { return Create<CTHPermissionGroupEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHPreMedication entity</summary>
		public EntityQuery<CTHPreMedicationEntity> CTHPreMedication { get { return Create<CTHPreMedicationEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHProtocolCycle entity</summary>
		public EntityQuery<CTHProtocolCycleEntity> CTHProtocolCycle { get { return Create<CTHProtocolCycleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHRole entity</summary>
		public EntityQuery<CTHRoleEntity> CTHRole { get { return Create<CTHRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHRolePermission entity</summary>
		public EntityQuery<CTHRolePermissionEntity> CTHRolePermission { get { return Create<CTHRolePermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSolution entity</summary>
		public EntityQuery<CTHSolutionEntity> CTHSolution { get { return Create<CTHSolutionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSpecialCase entity</summary>
		public EntityQuery<CTHSpecialCaseEntity> CTHSpecialCase { get { return Create<CTHSpecialCaseEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSpecialCasePart entity</summary>
		public EntityQuery<CTHSpecialCasePartEntity> CTHSpecialCasePart { get { return Create<CTHSpecialCasePartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHStaging entity</summary>
		public EntityQuery<CTHStagingEntity> CTHStaging { get { return Create<CTHStagingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSurgeryType entity</summary>
		public EntityQuery<CTHSurgeryTypeEntity> CTHSurgeryType { get { return Create<CTHSurgeryTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSymptom entity</summary>
		public EntityQuery<CTHSymptomEntity> CTHSymptom { get { return Create<CTHSymptomEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHSymptomDrug entity</summary>
		public EntityQuery<CTHSymptomDrugEntity> CTHSymptomDrug { get { return Create<CTHSymptomDrugEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHTNMStaging entity</summary>
		public EntityQuery<CTHTNMStagingEntity> CTHTNMStaging { get { return Create<CTHTNMStagingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHTNMStagingMatrix entity</summary>
		public EntityQuery<CTHTNMStagingMatrixEntity> CTHTNMStagingMatrix { get { return Create<CTHTNMStagingMatrixEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHTNMType entity</summary>
		public EntityQuery<CTHTNMTypeEntity> CTHTNMType { get { return Create<CTHTNMTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHTreatmentType entity</summary>
		public EntityQuery<CTHTreatmentTypeEntity> CTHTreatmentType { get { return Create<CTHTreatmentTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHTumorGrade entity</summary>
		public EntityQuery<CTHTumorGradeEntity> CTHTumorGrade { get { return Create<CTHTumorGradeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHUser entity</summary>
		public EntityQuery<CTHUserEntity> CTHUser { get { return Create<CTHUserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CTHUserRole entity</summary>
		public EntityQuery<CTHUserRoleEntity> CTHUserRole { get { return Create<CTHUserRoleEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}