//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.6.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SStorm.CTH.DAL.FactoryClasses;
using SStorm.CTH.DAL.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace SStorm.CTH.DAL.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCTHCancerGradeEntityInfo();
			InitCTHCancerHistologicEntityInfo();
			InitCTHCancerMolecularEntityInfo();
			InitCTHCancerSideEntityInfo();
			InitCTHCancerStagingEntityInfo();
			InitCTHCancerTypeEntityInfo();
			InitCTHChemoLabEntityInfo();
			InitCTHChemotherapyProtocolEntityInfo();
			InitCTHCycleDrugEntityInfo();
			InitCTHCycleLabEntityInfo();
			InitCTHDoctorEntityInfo();
			InitCTHDoseUnitEntityInfo();
			InitCTHDrugEntityInfo();
			InitCTHDrugAttachmentEntityInfo();
			InitCTHDrugDayEntityInfo();
			InitCTHDrugSymptomEntityInfo();
			InitCTHImagingEntityInfo();
			InitCTHKimoSurveyEntityInfo();
			InitCTHLabEntityInfo();
			InitCTHLabDetailEntityInfo();
			InitCTHLabDetailConditionEntityInfo();
			InitCTHLabGroupEntityInfo();
			InitCTHLabGroupLabEntityInfo();
			InitCTHMainCancerImageEntityInfo();
			InitCTHNotificationEntityInfo();
			InitCTHOperatorEntityInfo();
			InitCTHPathologyReportTypeEntityInfo();
			InitCTHPatientEntityInfo();
			InitCTHPatientAssessmentEntityInfo();
			InitCTHPatientClinicalDataEntityInfo();
			InitCTHPatientDrugEntityInfo();
			InitCTHPatientImagingEntityInfo();
			InitCTHPatientIntialLabEntityInfo();
			InitCTHPatientPathologyReportEntityInfo();
			InitCTHPatientSurgeryEntityInfo();
			InitCTHPatientSymptomEntityInfo();
			InitCTHPaymentTypeEntityInfo();
			InitCTHPermissionEntityInfo();
			InitCTHPermissionGroupEntityInfo();
			InitCTHPreMedicationEntityInfo();
			InitCTHProtocolCycleEntityInfo();
			InitCTHRoleEntityInfo();
			InitCTHRolePermissionEntityInfo();
			InitCTHSolutionEntityInfo();
			InitCTHSpecialCaseEntityInfo();
			InitCTHSpecialCasePartEntityInfo();
			InitCTHStagingEntityInfo();
			InitCTHSurgeryTypeEntityInfo();
			InitCTHSymptomEntityInfo();
			InitCTHSymptomDrugEntityInfo();
			InitCTHTNMStagingEntityInfo();
			InitCTHTNMStagingMatrixEntityInfo();
			InitCTHTNMTypeEntityInfo();
			InitCTHTreatmentTypeEntityInfo();
			InitCTHTumorGradeEntityInfo();
			InitCTHUserEntityInfo();
			InitCTHUserRoleEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CTHCancerGradeEntity's info objects</summary>
		private void InitCTHCancerGradeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerGradeFieldIndex), "CTHCancerGradeEntity");
			this.AddElementFieldInfo("CTHCancerGradeEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHCancerGradeFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerGradeEntity", "Grade", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHCancerGradeFieldIndex.Grade, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerGradeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerGradeFieldIndex.ID, 0, 0, 10);
		}

		/// <summary>Inits CTHCancerHistologicEntity's info objects</summary>
		private void InitCTHCancerHistologicEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerHistologicFieldIndex), "CTHCancerHistologicEntity");
			this.AddElementFieldInfo("CTHCancerHistologicEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHCancerHistologicFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerHistologicEntity", "CanerID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCancerHistologicFieldIndex.CanerID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerHistologicEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerHistologicFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerHistologicEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHCancerHistologicFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerHistologicEntity", "ParentID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCancerHistologicFieldIndex.ParentID, 0, 0, 10);
		}

		/// <summary>Inits CTHCancerMolecularEntity's info objects</summary>
		private void InitCTHCancerMolecularEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerMolecularFieldIndex), "CTHCancerMolecularEntity");
			this.AddElementFieldInfo("CTHCancerMolecularEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHCancerMolecularFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerMolecularEntity", "CanerID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCancerMolecularFieldIndex.CanerID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerMolecularEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerMolecularFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerMolecularEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHCancerMolecularFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerMolecularEntity", "ParentID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCancerMolecularFieldIndex.ParentID, 0, 0, 10);
		}

		/// <summary>Inits CTHCancerSideEntity's info objects</summary>
		private void InitCTHCancerSideEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerSideFieldIndex), "CTHCancerSideEntity");
			this.AddElementFieldInfo("CTHCancerSideEntity", "ArSide", typeof(System.String), false, false, false, true,  (int)CTHCancerSideFieldIndex.ArSide, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerSideEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerSideFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerSideEntity", "Side", typeof(System.String), false, false, false, true,  (int)CTHCancerSideFieldIndex.Side, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHCancerStagingEntity's info objects</summary>
		private void InitCTHCancerStagingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerStagingFieldIndex), "CTHCancerStagingEntity");
			this.AddElementFieldInfo("CTHCancerStagingEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHCancerStagingFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerStagingEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHCancerStagingFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerStagingEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerStagingFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerStagingEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHCancerStagingFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerStagingEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHCancerStagingFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerStagingEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHCancerStagingFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHCancerTypeEntity's info objects</summary>
		private void InitCTHCancerTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCancerTypeFieldIndex), "CTHCancerTypeEntity");
			this.AddElementFieldInfo("CTHCancerTypeEntity", "ArICDCode", typeof(System.String), false, false, false, true,  (int)CTHCancerTypeFieldIndex.ArICDCode, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "ArTypeName", typeof(System.String), false, false, false, true,  (int)CTHCancerTypeFieldIndex.ArTypeName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "ICDCode", typeof(System.String), false, false, false, true,  (int)CTHCancerTypeFieldIndex.ICDCode, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCancerTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "IsParent", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CTHCancerTypeFieldIndex.IsParent, 0, 0, 0);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "ParentID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCancerTypeFieldIndex.ParentID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCancerTypeEntity", "TypeName", typeof(System.String), false, false, false, true,  (int)CTHCancerTypeFieldIndex.TypeName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHChemoLabEntity's info objects</summary>
		private void InitCTHChemoLabEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHChemoLabFieldIndex), "CTHChemoLabEntity");
			this.AddElementFieldInfo("CTHChemoLabEntity", "ArTextResult", typeof(System.String), false, false, false, true,  (int)CTHChemoLabFieldIndex.ArTextResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemoLabEntity", "Attachment", typeof(System.String), false, false, false, true,  (int)CTHChemoLabFieldIndex.Attachment, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemoLabEntity", "AttachmentResult", typeof(System.String), false, false, false, true,  (int)CTHChemoLabFieldIndex.AttachmentResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemoLabEntity", "ChemoID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHChemoLabFieldIndex.ChemoID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemoLabEntity", "Date", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHChemoLabFieldIndex.Date, 0, 0, 0);
			this.AddElementFieldInfo("CTHChemoLabEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHChemoLabFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemoLabEntity", "LabDetailsID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHChemoLabFieldIndex.LabDetailsID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemoLabEntity", "TextResult", typeof(System.String), false, false, false, true,  (int)CTHChemoLabFieldIndex.TextResult, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHChemotherapyProtocolEntity's info objects</summary>
		private void InitCTHChemotherapyProtocolEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHChemotherapyProtocolFieldIndex), "CTHChemotherapyProtocolEntity");
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "AntimicrobialDrug", typeof(System.String), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.AntimicrobialDrug, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "ArProtocolName", typeof(System.String), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.ArProtocolName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHChemotherapyProtocolFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "Days", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.Days, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "EmetodenicRiskID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.EmetodenicRiskID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "GrowthFactorDrug", typeof(System.String), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.GrowthFactorDrug, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHChemotherapyProtocolFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "IsAntimicrobial", typeof(System.Boolean), false, false, false, false,  (int)CTHChemotherapyProtocolFieldIndex.IsAntimicrobial, 0, 0, 0);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "IsGrowthFactor", typeof(System.Boolean), false, false, false, false,  (int)CTHChemotherapyProtocolFieldIndex.IsGrowthFactor, 0, 0, 0);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "PremedicationID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHChemotherapyProtocolFieldIndex.PremedicationID, 0, 0, 10);
			this.AddElementFieldInfo("CTHChemotherapyProtocolEntity", "ProtocolName", typeof(System.String), false, false, false, true,  (int)CTHChemotherapyProtocolFieldIndex.ProtocolName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHCycleDrugEntity's info objects</summary>
		private void InitCTHCycleDrugEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCycleDrugFieldIndex), "CTHCycleDrugEntity");
			this.AddElementFieldInfo("CTHCycleDrugEntity", "CycleID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCycleDrugFieldIndex.CycleID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCycleDrugEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCycleDrugFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCycleDrugEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCycleDrugFieldIndex.ID, 0, 0, 10);
		}

		/// <summary>Inits CTHCycleLabEntity's info objects</summary>
		private void InitCTHCycleLabEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHCycleLabFieldIndex), "CTHCycleLabEntity");
			this.AddElementFieldInfo("CTHCycleLabEntity", "CycleID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCycleLabFieldIndex.CycleID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCycleLabEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHCycleLabFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHCycleLabEntity", "LabID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHCycleLabFieldIndex.LabID, 0, 0, 10);
		}

		/// <summary>Inits CTHDoctorEntity's info objects</summary>
		private void InitCTHDoctorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDoctorFieldIndex), "CTHDoctorEntity");
			this.AddElementFieldInfo("CTHDoctorEntity", "ArContactNumber", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.ArContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "ArDegree", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.ArDegree, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "ContactNumber", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.ContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "Degree", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.Degree, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDoctorFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDoctorEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHDoctorFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoctorEntity", "UserID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDoctorFieldIndex.UserID, 0, 0, 10);
		}

		/// <summary>Inits CTHDoseUnitEntity's info objects</summary>
		private void InitCTHDoseUnitEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDoseUnitFieldIndex), "CTHDoseUnitEntity");
			this.AddElementFieldInfo("CTHDoseUnitEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHDoseUnitFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDoseUnitEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDoseUnitFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDoseUnitEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHDoseUnitFieldIndex.Name, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHDrugEntity's info objects</summary>
		private void InitCTHDrugEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDrugFieldIndex), "CTHDrugEntity");
			this.AddElementFieldInfo("CTHDrugEntity", "ArFinalConcentration", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.ArFinalConcentration, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "ArSpecialAdminstrationNotes", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.ArSpecialAdminstrationNotes, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "ArTimeOfAdminstration", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.ArTimeOfAdminstration, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "Dose", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHDrugFieldIndex.Dose, 0, 0, 38);
			this.AddElementFieldInfo("CTHDrugEntity", "DosePerID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.DosePerID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "DoseUnitID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugFieldIndex.DoseUnitID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "Duration", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.Duration, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "DurationUnitID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.DurationUnitID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "Every", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.Every, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "EveryUnitID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.EveryUnitID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "FinalConcentration", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.FinalConcentration, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "FormAmount", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.FormAmount, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "FormID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.FormID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDrugFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "ProtocolID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugFieldIndex.ProtocolID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "RouteID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.RouteID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "SolutionAmount", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugFieldIndex.SolutionAmount, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "SolutionID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugFieldIndex.SolutionID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugEntity", "SpecialAdminstrationNotes", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.SpecialAdminstrationNotes, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugEntity", "TimeOfAdminstration", typeof(System.String), false, false, false, true,  (int)CTHDrugFieldIndex.TimeOfAdminstration, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHDrugAttachmentEntity's info objects</summary>
		private void InitCTHDrugAttachmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDrugAttachmentFieldIndex), "CTHDrugAttachmentEntity");
			this.AddElementFieldInfo("CTHDrugAttachmentEntity", "Attachment", typeof(System.String), false, false, false, true,  (int)CTHDrugAttachmentFieldIndex.Attachment, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHDrugAttachmentEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugAttachmentFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugAttachmentEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDrugAttachmentFieldIndex.ID, 0, 0, 10);
		}

		/// <summary>Inits CTHDrugDayEntity's info objects</summary>
		private void InitCTHDrugDayEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDrugDayFieldIndex), "CTHDrugDayEntity");
			this.AddElementFieldInfo("CTHDrugDayEntity", "Day", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHDrugDayFieldIndex.Day, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugDayEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugDayFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugDayEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDrugDayFieldIndex.ID, 0, 0, 10);
		}

		/// <summary>Inits CTHDrugSymptomEntity's info objects</summary>
		private void InitCTHDrugSymptomEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHDrugSymptomFieldIndex), "CTHDrugSymptomEntity");
			this.AddElementFieldInfo("CTHDrugSymptomEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugSymptomFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugSymptomEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHDrugSymptomFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHDrugSymptomEntity", "SymtomID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHDrugSymptomFieldIndex.SymtomID, 0, 0, 10);
		}

		/// <summary>Inits CTHImagingEntity's info objects</summary>
		private void InitCTHImagingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHImagingFieldIndex), "CTHImagingEntity");
			this.AddElementFieldInfo("CTHImagingEntity", "ArImageName", typeof(System.String), false, false, false, true,  (int)CTHImagingFieldIndex.ArImageName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHImagingEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHImagingFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHImagingEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHImagingFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHImagingEntity", "ImageName", typeof(System.String), false, false, false, true,  (int)CTHImagingFieldIndex.ImageName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHImagingEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHImagingFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHKimoSurveyEntity's info objects</summary>
		private void InitCTHKimoSurveyEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHKimoSurveyFieldIndex), "CTHKimoSurveyEntity");
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "AdjustBodyWeight", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.AdjustBodyWeight, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "BodyMassIndex", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.BodyMassIndex, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "BodySurfaceArea", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.BodySurfaceArea, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "BodySurfaceAreaInAdultAmputees", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.BodySurfaceAreaInAdultAmputees, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "CRCL", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.CRCL, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "CycleID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.CycleID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "CycleNum", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.CycleNum, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "Date", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.Date, 0, 0, 0);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "Days", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.Days, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "Height", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.Height, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHKimoSurveyFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "IsSpecialCase", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.IsSpecialCase, 0, 0, 0);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "LeanBodyWeight", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.LeanBodyWeight, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "PatientClinicalDataID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.PatientClinicalDataID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "ProtocolID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.ProtocolID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "SerumCreatinine", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.SerumCreatinine, 0, 3, 18);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "SpecialCaseID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.SpecialCaseID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "SpecialCasePartID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.SpecialCasePartID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "TreatementTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHKimoSurveyFieldIndex.TreatementTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHKimoSurveyEntity", "Weight", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CTHKimoSurveyFieldIndex.Weight, 0, 3, 18);
		}

		/// <summary>Inits CTHLabEntity's info objects</summary>
		private void InitCTHLabEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHLabFieldIndex), "CTHLabEntity");
			this.AddElementFieldInfo("CTHLabEntity", "ArLabName", typeof(System.String), false, false, false, true,  (int)CTHLabFieldIndex.ArLabName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHLabFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHLabFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabEntity", "IsIntial", typeof(System.Boolean), false, false, false, false,  (int)CTHLabFieldIndex.IsIntial, 0, 0, 0);
			this.AddElementFieldInfo("CTHLabEntity", "IsMandatory", typeof(System.Boolean), false, false, false, false,  (int)CTHLabFieldIndex.IsMandatory, 0, 0, 0);
			this.AddElementFieldInfo("CTHLabEntity", "LabName", typeof(System.String), false, false, false, true,  (int)CTHLabFieldIndex.LabName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabEntity", "ProtocolID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabFieldIndex.ProtocolID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHLabFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHLabDetailEntity's info objects</summary>
		private void InitCTHLabDetailEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHLabDetailFieldIndex), "CTHLabDetailEntity");
			this.AddElementFieldInfo("CTHLabDetailEntity", "ArLabDetailsName", typeof(System.String), false, false, false, true,  (int)CTHLabDetailFieldIndex.ArLabDetailsName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHLabDetailFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHLabDetailFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabDetailEntity", "LabDetailsName", typeof(System.String), false, false, false, true,  (int)CTHLabDetailFieldIndex.LabDetailsName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailEntity", "LabID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabDetailFieldIndex.LabID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabDetailEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHLabDetailFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHLabDetailConditionEntity's info objects</summary>
		private void InitCTHLabDetailConditionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHLabDetailConditionFieldIndex), "CTHLabDetailConditionEntity");
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "ArCondition", typeof(System.String), false, false, false, true,  (int)CTHLabDetailConditionFieldIndex.ArCondition, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "ArMessage", typeof(System.String), false, false, false, true,  (int)CTHLabDetailConditionFieldIndex.ArMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "Condition", typeof(System.String), false, false, false, true,  (int)CTHLabDetailConditionFieldIndex.Condition, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHLabDetailConditionFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "LabDetailID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabDetailConditionFieldIndex.LabDetailID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "Message", typeof(System.String), false, false, false, true,  (int)CTHLabDetailConditionFieldIndex.Message, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHLabDetailConditionFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabDetailConditionEntity", "OpertorID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabDetailConditionFieldIndex.OpertorID, 0, 0, 10);
		}

		/// <summary>Inits CTHLabGroupEntity's info objects</summary>
		private void InitCTHLabGroupEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHLabGroupFieldIndex), "CTHLabGroupEntity");
			this.AddElementFieldInfo("CTHLabGroupEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHLabGroupFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabGroupEntity", "LabGroupName", typeof(System.String), false, false, false, true,  (int)CTHLabGroupFieldIndex.LabGroupName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHLabGroupLabEntity's info objects</summary>
		private void InitCTHLabGroupLabEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHLabGroupLabFieldIndex), "CTHLabGroupLabEntity");
			this.AddElementFieldInfo("CTHLabGroupLabEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHLabGroupLabFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabGroupLabEntity", "LabGroupID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabGroupLabFieldIndex.LabGroupID, 0, 0, 10);
			this.AddElementFieldInfo("CTHLabGroupLabEntity", "LabID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHLabGroupLabFieldIndex.LabID, 0, 0, 10);
		}

		/// <summary>Inits CTHMainCancerImageEntity's info objects</summary>
		private void InitCTHMainCancerImageEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHMainCancerImageFieldIndex), "CTHMainCancerImageEntity");
			this.AddElementFieldInfo("CTHMainCancerImageEntity", "HematologicTumorImage", typeof(System.String), false, false, false, true,  (int)CTHMainCancerImageFieldIndex.HematologicTumorImage, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHMainCancerImageEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHMainCancerImageFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHMainCancerImageEntity", "ImageNum", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHMainCancerImageFieldIndex.ImageNum, 0, 0, 10);
			this.AddElementFieldInfo("CTHMainCancerImageEntity", "SolidTumorImage", typeof(System.String), false, false, false, true,  (int)CTHMainCancerImageFieldIndex.SolidTumorImage, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHNotificationEntity's info objects</summary>
		private void InitCTHNotificationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHNotificationFieldIndex), "CTHNotificationEntity");
			this.AddElementFieldInfo("CTHNotificationEntity", "ArMessage", typeof(System.String), false, false, false, true,  (int)CTHNotificationFieldIndex.ArMessage, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHNotificationEntity", "DoctorID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHNotificationFieldIndex.DoctorID, 0, 0, 10);
			this.AddElementFieldInfo("CTHNotificationEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHNotificationFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHNotificationEntity", "KimoID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHNotificationFieldIndex.KimoID, 0, 0, 10);
			this.AddElementFieldInfo("CTHNotificationEntity", "Message", typeof(System.String), false, false, false, true,  (int)CTHNotificationFieldIndex.Message, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHNotificationEntity", "NotificationDate", typeof(System.DateTime), false, false, false, false,  (int)CTHNotificationFieldIndex.NotificationDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHNotificationEntity", "PatientID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHNotificationFieldIndex.PatientID, 0, 0, 10);
			this.AddElementFieldInfo("CTHNotificationEntity", "PatientSymptomID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHNotificationFieldIndex.PatientSymptomID, 0, 0, 10);
			this.AddElementFieldInfo("CTHNotificationEntity", "Seen", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CTHNotificationFieldIndex.Seen, 0, 0, 0);
			this.AddElementFieldInfo("CTHNotificationEntity", "TypeID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHNotificationFieldIndex.TypeID, 0, 0, 10);
		}

		/// <summary>Inits CTHOperatorEntity's info objects</summary>
		private void InitCTHOperatorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHOperatorFieldIndex), "CTHOperatorEntity");
			this.AddElementFieldInfo("CTHOperatorEntity", "ArOperatorName", typeof(System.String), false, false, false, true,  (int)CTHOperatorFieldIndex.ArOperatorName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHOperatorEntity", "ID", typeof(System.Int32), true, false, false, false,  (int)CTHOperatorFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHOperatorEntity", "OpertorIcon", typeof(System.String), false, false, false, true,  (int)CTHOperatorFieldIndex.OpertorIcon, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHOperatorEntity", "OpertorName", typeof(System.String), false, false, false, true,  (int)CTHOperatorFieldIndex.OpertorName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPathologyReportTypeEntity's info objects</summary>
		private void InitCTHPathologyReportTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPathologyReportTypeFieldIndex), "CTHPathologyReportTypeEntity");
			this.AddElementFieldInfo("CTHPathologyReportTypeEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHPathologyReportTypeFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPathologyReportTypeEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHPathologyReportTypeFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPathologyReportTypeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPathologyReportTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPathologyReportTypeEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHPathologyReportTypeFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPathologyReportTypeEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHPathologyReportTypeFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPatientEntity's info objects</summary>
		private void InitCTHPatientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientFieldIndex), "CTHPatientEntity");
			this.AddElementFieldInfo("CTHPatientEntity", "ArCareProviderContactNumber", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArCareProviderContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArCareProviderName", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArCareProviderName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArCareProviderTitle", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArCareProviderTitle, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArContactNumber", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArNationalID", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArNationalID, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArOccupation", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArOccupation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArPatientGender", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArPatientGender, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArResidence", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArResidence, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ArSponserCompanyName", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ArSponserCompanyName, 10, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "BirthDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientFieldIndex.BirthDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "CareProviderContactNumber", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.CareProviderContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "CareProviderName", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.CareProviderName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "CareProviderTitle", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.CareProviderTitle, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ContactNumber", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.ContactNumber, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "DoctorID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientFieldIndex.DoctorID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientEntity", "FirstVisitDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientFieldIndex.FirstVisitDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientEntity", "NationalID", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.NationalID, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "NationalIDPhotoPath", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.NationalIDPhotoPath, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "Occupation", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.Occupation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "PatientAge", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHPatientFieldIndex.PatientAge, 0, 0, 38);
			this.AddElementFieldInfo("CTHPatientEntity", "PatientGender", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.PatientGender, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "PatientNameA", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.PatientNameA, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "PatientNameE", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.PatientNameE, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "PatientNumber", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientFieldIndex.PatientNumber, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientEntity", "PaymentTypeId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientFieldIndex.PaymentTypeId, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientEntity", "Residence", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.Residence, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "SponserCompanyName", typeof(System.String), false, false, false, true,  (int)CTHPatientFieldIndex.SponserCompanyName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientEntity", "UserID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientFieldIndex.UserID, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientAssessmentEntity's info objects</summary>
		private void InitCTHPatientAssessmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientAssessmentFieldIndex), "CTHPatientAssessmentEntity");
			this.AddElementFieldInfo("CTHPatientAssessmentEntity", "Date", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientAssessmentFieldIndex.Date, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientAssessmentEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientAssessmentFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientAssessmentEntity", "PatientID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientAssessmentFieldIndex.PatientID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientAssessmentEntity", "TreatmentPlanID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientAssessmentFieldIndex.TreatmentPlanID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientAssessmentEntity", "TreatmentResponseID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientAssessmentFieldIndex.TreatmentResponseID, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientClinicalDataEntity's info objects</summary>
		private void InitCTHPatientClinicalDataEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientClinicalDataFieldIndex), "CTHPatientClinicalDataEntity");
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "CancerHistologicalID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.CancerHistologicalID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "CancerMolecularID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.CancerMolecularID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "CancerSideId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.CancerSideId, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "DataDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientClinicalDataFieldIndex.DataDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientClinicalDataFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "PatientID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.PatientID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "StageGradeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.StageGradeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientClinicalDataEntity", "TumorGradeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientClinicalDataFieldIndex.TumorGradeID, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientDrugEntity's info objects</summary>
		private void InitCTHPatientDrugEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientDrugFieldIndex), "CTHPatientDrugEntity");
			this.AddElementFieldInfo("CTHPatientDrugEntity", "Date", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.Date, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "Dose", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.Dose, 0, 0, 38);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "DoseModification", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.DoseModification, 0, 0, 38);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "DosePer", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.DosePer, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "DoseUnit", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.DoseUnit, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "DrugDayID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientDrugFieldIndex.DrugDayID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientDrugFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientDrugFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "IsNewDrug", typeof(System.Boolean), false, false, false, false,  (int)CTHPatientDrugFieldIndex.IsNewDrug, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "KimoID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientDrugFieldIndex.KimoID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientDrugEntity", "RouteID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientDrugFieldIndex.RouteID, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientImagingEntity's info objects</summary>
		private void InitCTHPatientImagingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientImagingFieldIndex), "CTHPatientImagingEntity");
			this.AddElementFieldInfo("CTHPatientImagingEntity", "ArTextResult", typeof(System.String), false, false, false, true,  (int)CTHPatientImagingFieldIndex.ArTextResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "AttachmentResult", typeof(System.String), false, false, false, true,  (int)CTHPatientImagingFieldIndex.AttachmentResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientImagingFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "Image", typeof(System.String), false, false, false, true,  (int)CTHPatientImagingFieldIndex.Image, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "ImagingTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientImagingFieldIndex.ImagingTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "PatientClinicalDataID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientImagingFieldIndex.PatientClinicalDataID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientImagingEntity", "TextResult", typeof(System.String), false, false, false, true,  (int)CTHPatientImagingFieldIndex.TextResult, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPatientIntialLabEntity's info objects</summary>
		private void InitCTHPatientIntialLabEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientIntialLabFieldIndex), "CTHPatientIntialLabEntity");
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "ArTextResult", typeof(System.String), false, false, false, true,  (int)CTHPatientIntialLabFieldIndex.ArTextResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "AttachmentResult", typeof(System.String), false, false, false, true,  (int)CTHPatientIntialLabFieldIndex.AttachmentResult, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientIntialLabFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "LabID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientIntialLabFieldIndex.LabID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "PatientClinicalDataID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientIntialLabFieldIndex.PatientClinicalDataID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "PatientLabFile", typeof(System.String), false, false, false, true,  (int)CTHPatientIntialLabFieldIndex.PatientLabFile, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientIntialLabEntity", "TextResult", typeof(System.String), false, false, false, true,  (int)CTHPatientIntialLabFieldIndex.TextResult, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPatientPathologyReportEntity's info objects</summary>
		private void InitCTHPatientPathologyReportEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientPathologyReportFieldIndex), "CTHPatientPathologyReportEntity");
			this.AddElementFieldInfo("CTHPatientPathologyReportEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientPathologyReportFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientPathologyReportEntity", "PatienClinicalDataID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientPathologyReportFieldIndex.PatienClinicalDataID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientPathologyReportEntity", "Report", typeof(System.String), false, false, false, true,  (int)CTHPatientPathologyReportFieldIndex.Report, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientPathologyReportEntity", "ReportTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientPathologyReportFieldIndex.ReportTypeID, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientSurgeryEntity's info objects</summary>
		private void InitCTHPatientSurgeryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientSurgeryFieldIndex), "CTHPatientSurgeryEntity");
			this.AddElementFieldInfo("CTHPatientSurgeryEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientSurgeryFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSurgeryEntity", "PatientClinicalDataID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientSurgeryFieldIndex.PatientClinicalDataID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSurgeryEntity", "SurgeryDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientSurgeryFieldIndex.SurgeryDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientSurgeryEntity", "SurgeryTypeId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientSurgeryFieldIndex.SurgeryTypeId, 0, 0, 10);
		}

		/// <summary>Inits CTHPatientSymptomEntity's info objects</summary>
		private void InitCTHPatientSymptomEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPatientSymptomFieldIndex), "CTHPatientSymptomEntity");
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "ArDoctorRecommendation", typeof(System.String), false, false, false, true,  (int)CTHPatientSymptomFieldIndex.ArDoctorRecommendation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "ChemoID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientSymptomFieldIndex.ChemoID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "Date", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHPatientSymptomFieldIndex.Date, 0, 0, 0);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "EnDoctorRecommendation", typeof(System.String), false, false, false, true,  (int)CTHPatientSymptomFieldIndex.EnDoctorRecommendation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPatientSymptomFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "PatientID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientSymptomFieldIndex.PatientID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "SymptomDurationAmount", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientSymptomFieldIndex.SymptomDurationAmount, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "SymptomDurationUnit", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPatientSymptomFieldIndex.SymptomDurationUnit, 0, 0, 10);
			this.AddElementFieldInfo("CTHPatientSymptomEntity", "SymptomID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPatientSymptomFieldIndex.SymptomID, 0, 0, 10);
		}

		/// <summary>Inits CTHPaymentTypeEntity's info objects</summary>
		private void InitCTHPaymentTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPaymentTypeFieldIndex), "CTHPaymentTypeEntity");
			this.AddElementFieldInfo("CTHPaymentTypeEntity", "ArPaymentType", typeof(System.String), false, false, false, true,  (int)CTHPaymentTypeFieldIndex.ArPaymentType, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPaymentTypeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPaymentTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPaymentTypeEntity", "PaymentType", typeof(System.String), false, false, false, true,  (int)CTHPaymentTypeFieldIndex.PaymentType, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPermissionEntity's info objects</summary>
		private void InitCTHPermissionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPermissionFieldIndex), "CTHPermissionEntity");
			this.AddElementFieldInfo("CTHPermissionEntity", "ArPermissionName", typeof(System.String), false, false, false, true,  (int)CTHPermissionFieldIndex.ArPermissionName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPermissionEntity", "GroupID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHPermissionFieldIndex.GroupID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPermissionEntity", "ID", typeof(System.Int32), true, false, false, false,  (int)CTHPermissionFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPermissionEntity", "PermissionName", typeof(System.String), false, false, false, true,  (int)CTHPermissionFieldIndex.PermissionName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHPermissionGroupEntity's info objects</summary>
		private void InitCTHPermissionGroupEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPermissionGroupFieldIndex), "CTHPermissionGroupEntity");
			this.AddElementFieldInfo("CTHPermissionGroupEntity", "ArGroupName", typeof(System.String), false, false, false, true,  (int)CTHPermissionGroupFieldIndex.ArGroupName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPermissionGroupEntity", "GroupName", typeof(System.String), false, false, false, true,  (int)CTHPermissionGroupFieldIndex.GroupName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPermissionGroupEntity", "ID", typeof(System.Int32), true, false, false, false,  (int)CTHPermissionGroupFieldIndex.ID, 0, 0, 10);
		}

		/// <summary>Inits CTHPreMedicationEntity's info objects</summary>
		private void InitCTHPreMedicationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHPreMedicationFieldIndex), "CTHPreMedicationEntity");
			this.AddElementFieldInfo("CTHPreMedicationEntity", "ArDescription", typeof(System.String), false, false, false, true,  (int)CTHPreMedicationFieldIndex.ArDescription, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "ArTitle", typeof(System.String), false, false, false, true,  (int)CTHPreMedicationFieldIndex.ArTitle, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHPreMedicationFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "EmetogenicID", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPreMedicationFieldIndex.EmetogenicID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHPreMedicationFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHPreMedicationFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHPreMedicationEntity", "Title", typeof(System.String), false, false, false, true,  (int)CTHPreMedicationFieldIndex.Title, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHProtocolCycleEntity's info objects</summary>
		private void InitCTHProtocolCycleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHProtocolCycleFieldIndex), "CTHProtocolCycleEntity");
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "Every", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.Every, 0, 0, 10);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "EveryUnit", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.EveryUnit, 0, 0, 10);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHProtocolCycleFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "NotifyAfterCycle", typeof(System.Boolean), false, false, false, false,  (int)CTHProtocolCycleFieldIndex.NotifyAfterCycle, 0, 0, 0);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "ProtocolID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHProtocolCycleFieldIndex.ProtocolID, 0, 0, 10);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "RecycleDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.RecycleDate, 0, 0, 0);
			this.AddElementFieldInfo("CTHProtocolCycleEntity", "RecyclingAfter", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHProtocolCycleFieldIndex.RecyclingAfter, 0, 0, 10);
		}

		/// <summary>Inits CTHRoleEntity's info objects</summary>
		private void InitCTHRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHRoleFieldIndex), "CTHRoleEntity");
			this.AddElementFieldInfo("CTHRoleEntity", "ArRoleNmae", typeof(System.String), false, false, false, true,  (int)CTHRoleFieldIndex.ArRoleNmae, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHRoleEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHRoleFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHRoleEntity", "RoleNmae", typeof(System.String), false, false, false, true,  (int)CTHRoleFieldIndex.RoleNmae, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHRolePermissionEntity's info objects</summary>
		private void InitCTHRolePermissionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHRolePermissionFieldIndex), "CTHRolePermissionEntity");
			this.AddElementFieldInfo("CTHRolePermissionEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHRolePermissionFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHRolePermissionEntity", "PermissionID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHRolePermissionFieldIndex.PermissionID, 0, 0, 10);
			this.AddElementFieldInfo("CTHRolePermissionEntity", "RoleID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHRolePermissionFieldIndex.RoleID, 0, 0, 10);
		}

		/// <summary>Inits CTHSolutionEntity's info objects</summary>
		private void InitCTHSolutionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSolutionFieldIndex), "CTHSolutionEntity");
			this.AddElementFieldInfo("CTHSolutionEntity", "ArDescription", typeof(System.String), false, false, false, true,  (int)CTHSolutionFieldIndex.ArDescription, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSolutionEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHSolutionFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSolutionEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHSolutionFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSolutionEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSolutionFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSolutionEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHSolutionFieldIndex.Name, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHSpecialCaseEntity's info objects</summary>
		private void InitCTHSpecialCaseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSpecialCaseFieldIndex), "CTHSpecialCaseEntity");
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "ArCaseName", typeof(System.String), false, false, false, true,  (int)CTHSpecialCaseFieldIndex.ArCaseName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHSpecialCaseFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "CaseName", typeof(System.String), false, false, false, true,  (int)CTHSpecialCaseFieldIndex.CaseName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "HasParts", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CTHSpecialCaseFieldIndex.HasParts, 0, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSpecialCaseFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSpecialCaseEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHSpecialCaseFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHSpecialCasePartEntity's info objects</summary>
		private void InitCTHSpecialCasePartEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSpecialCasePartFieldIndex), "CTHSpecialCasePartEntity");
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "ArPartName", typeof(System.String), false, false, false, true,  (int)CTHSpecialCasePartFieldIndex.ArPartName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHSpecialCasePartFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "CaseID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHSpecialCasePartFieldIndex.CaseID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSpecialCasePartFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "PartName", typeof(System.String), false, false, false, true,  (int)CTHSpecialCasePartFieldIndex.PartName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSpecialCasePartEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHSpecialCasePartFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHStagingEntity's info objects</summary>
		private void InitCTHStagingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHStagingFieldIndex), "CTHStagingEntity");
			this.AddElementFieldInfo("CTHStagingEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHStagingFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHStagingEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHStagingFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHStagingEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHStagingFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHStagingEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHStagingFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHStagingEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHStagingFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHStagingEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHStagingFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHStagingEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHStagingFieldIndex.Remarks, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHSurgeryTypeEntity's info objects</summary>
		private void InitCTHSurgeryTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSurgeryTypeFieldIndex), "CTHSurgeryTypeEntity");
			this.AddElementFieldInfo("CTHSurgeryTypeEntity", "ArSurgeryType", typeof(System.String), false, false, false, true,  (int)CTHSurgeryTypeFieldIndex.ArSurgeryType, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSurgeryTypeEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHSurgeryTypeFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSurgeryTypeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSurgeryTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSurgeryTypeEntity", "SurgeryType", typeof(System.String), false, false, false, true,  (int)CTHSurgeryTypeFieldIndex.SurgeryType, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHSymptomEntity's info objects</summary>
		private void InitCTHSymptomEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSymptomFieldIndex), "CTHSymptomEntity");
			this.AddElementFieldInfo("CTHSymptomEntity", "AlertColor", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.AlertColor, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "ArDescription", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.ArDescription, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "ArRecommendation", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.ArRecommendation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "ArResponse", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.ArResponse, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "Grade", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHSymptomFieldIndex.Grade, 0, 0, 10);
			this.AddElementFieldInfo("CTHSymptomEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSymptomFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSymptomEntity", "IsDoseLimitingToxicity", typeof(System.Boolean), false, false, false, false,  (int)CTHSymptomFieldIndex.IsDoseLimitingToxicity, 0, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "Recommendation", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.Recommendation, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHSymptomEntity", "Response", typeof(System.String), false, false, false, true,  (int)CTHSymptomFieldIndex.Response, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHSymptomDrugEntity's info objects</summary>
		private void InitCTHSymptomDrugEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHSymptomDrugFieldIndex), "CTHSymptomDrugEntity");
			this.AddElementFieldInfo("CTHSymptomDrugEntity", "DrugID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHSymptomDrugFieldIndex.DrugID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSymptomDrugEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHSymptomDrugFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHSymptomDrugEntity", "SymptomId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHSymptomDrugFieldIndex.SymptomId, 0, 0, 10);
		}

		/// <summary>Inits CTHTNMStagingEntity's info objects</summary>
		private void InitCTHTNMStagingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHTNMStagingFieldIndex), "CTHTNMStagingEntity");
			this.AddElementFieldInfo("CTHTNMStagingEntity", "ArDescription", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.ArDescription, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "ArName", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.ArName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "ArRemarks", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.ArRemarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHTNMStagingFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "Name", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.Name, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "Number", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHTNMStagingFieldIndex.Number, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)CTHTNMStagingFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "TNMFrom", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHTNMStagingFieldIndex.TNMFrom, 0, 0, 38);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "TNMTo", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHTNMStagingFieldIndex.TNMTo, 0, 0, 38);
			this.AddElementFieldInfo("CTHTNMStagingEntity", "TNMTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingFieldIndex.TNMTypeID, 0, 0, 10);
		}

		/// <summary>Inits CTHTNMStagingMatrixEntity's info objects</summary>
		private void InitCTHTNMStagingMatrixEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHTNMStagingMatrixFieldIndex), "CTHTNMStagingMatrixEntity");
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "CancerTypeID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingMatrixFieldIndex.CancerTypeID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHTNMStagingMatrixFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "MID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingMatrixFieldIndex.MID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "NID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingMatrixFieldIndex.NID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "StageID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingMatrixFieldIndex.StageID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMStagingMatrixEntity", "TID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHTNMStagingMatrixFieldIndex.TID, 0, 0, 10);
		}

		/// <summary>Inits CTHTNMTypeEntity's info objects</summary>
		private void InitCTHTNMTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHTNMTypeFieldIndex), "CTHTNMTypeEntity");
			this.AddElementFieldInfo("CTHTNMTypeEntity", "ArTypeName", typeof(System.String), false, false, false, true,  (int)CTHTNMTypeFieldIndex.ArTypeName, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTNMTypeEntity", "ID", typeof(System.Int32), true, false, false, false,  (int)CTHTNMTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTNMTypeEntity", "TypeName", typeof(System.String), false, false, false, true,  (int)CTHTNMTypeFieldIndex.TypeName, 2147483647, 0, 0);
		}

		/// <summary>Inits CTHTreatmentTypeEntity's info objects</summary>
		private void InitCTHTreatmentTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHTreatmentTypeFieldIndex), "CTHTreatmentTypeEntity");
			this.AddElementFieldInfo("CTHTreatmentTypeEntity", "ArTreatmentType", typeof(System.String), false, false, false, true,  (int)CTHTreatmentTypeFieldIndex.ArTreatmentType, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTreatmentTypeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHTreatmentTypeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTreatmentTypeEntity", "TreatmentType", typeof(System.String), false, false, false, true,  (int)CTHTreatmentTypeFieldIndex.TreatmentType, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTreatmentTypeEntity", "WhatTreatment", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CTHTreatmentTypeFieldIndex.WhatTreatment, 0, 0, 10);
		}

		/// <summary>Inits CTHTumorGradeEntity's info objects</summary>
		private void InitCTHTumorGradeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHTumorGradeFieldIndex), "CTHTumorGradeEntity");
			this.AddElementFieldInfo("CTHTumorGradeEntity", "Description", typeof(System.String), false, false, false, true,  (int)CTHTumorGradeFieldIndex.Description, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHTumorGradeEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHTumorGradeFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHTumorGradeEntity", "TumorGrade", typeof(Nullable<System.Double>), false, false, false, true,  (int)CTHTumorGradeFieldIndex.TumorGrade, 0, 0, 38);
		}

		/// <summary>Inits CTHUserEntity's info objects</summary>
		private void InitCTHUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHUserFieldIndex), "CTHUserEntity");
			this.AddElementFieldInfo("CTHUserEntity", "Email", typeof(System.String), false, false, false, true,  (int)CTHUserFieldIndex.Email, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHUserEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHUserFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHUserEntity", "Password", typeof(System.String), false, false, false, true,  (int)CTHUserFieldIndex.Password, 2147483647, 0, 0);
			this.AddElementFieldInfo("CTHUserEntity", "UserName", typeof(System.String), false, false, false, true,  (int)CTHUserFieldIndex.UserName, 50, 0, 0);
		}

		/// <summary>Inits CTHUserRoleEntity's info objects</summary>
		private void InitCTHUserRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CTHUserRoleFieldIndex), "CTHUserRoleEntity");
			this.AddElementFieldInfo("CTHUserRoleEntity", "ID", typeof(System.Int32), true, false, true, false,  (int)CTHUserRoleFieldIndex.ID, 0, 0, 10);
			this.AddElementFieldInfo("CTHUserRoleEntity", "RoleID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHUserRoleFieldIndex.RoleID, 0, 0, 10);
			this.AddElementFieldInfo("CTHUserRoleEntity", "UserID", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CTHUserRoleFieldIndex.UserID, 0, 0, 10);
		}
	}
}